/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    landing: Landing;
  };
  globalsSelect: {
    landing: LandingSelect<false> | LandingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown in the admin panel header.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Brand logos, testimonial posters, and any other image used on the landing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers. For a logo, the brand name is enough.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    logo?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    poster?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        logo?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        poster?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Every piece of copy on get.growthrush.ai. Saving republishes the live page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: number;
  brand: {
    name: string;
    /**
     * Rendered in the accent colour, e.g. .ai
     */
    suffix: string;
    tagline: string;
  };
  /**
   * Shown in the header and the footer, in this order. Any section on the page can be linked here, as long as it currently has content.
   */
  navLinks?:
    | {
        /**
         * The wording a visitor sees, e.g. “Tracks”.
         */
        label: string;
        /**
         * The section this link scrolls to, by its target ID. Only sections currently on the page are offered.
         */
        targetId: string;
        id?: string | null;
      }[]
    | null;
  announcement: {
    live: string;
    countdownLabel: string;
  };
  /**
   * The countdown counts down to this moment. Push it forward when a new cohort opens.
   */
  applicationsCloseAt: string;
  stickyBar: {
    title: string;
    sub: string;
    cta: string;
  };
  footer: {
    company: string;
    blurb: string;
    /**
     * Third-party brand disclaimer. Check any wording change with counsel before saving.
     */
    legal: string;
  };
  /**
   * Renders the "Hero" section, which is always part of the page.
   */
  hero: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "hero".
     */
    targetId?: string | null;
    kicker: string;
    titleLead: string;
    /**
     * Second line, rendered in the accent colour.
     */
    titleAccent: string;
    lede: string;
    /**
     * The 'without…' reassurance bullets.
     */
    checks?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * The duration / format / outcome strip.
     */
    glance?:
      | {
          /**
           * e.g. 300+, ₹250 Cr, 14 mo
           */
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    cta: string;
    ctaNote: string;
    credential: {
      /**
       * Fallback letter if the logo fails to load.
       */
      initial: string;
      logo?: (number | null) | Media;
      headline: string;
      body: string;
    };
    mapCaption: string;
  };
  /**
   * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "proof".
   */
  proofTargetId?: string | null;
  /**
   * The counter strip under the hero. Renders the "Proof stats" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  proofStats?:
    | {
        /**
         * e.g. 300+, ₹250 Cr, 14 mo
         */
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "clients".
   */
  clientsTargetId?: string | null;
  /**
   * Small label above the client logo row. The logos themselves come from the public/logos folder in the codebase, not from here.
   */
  showcaseHeading: string;
  /**
   * Renders the "The problem" section, which is always part of the page.
   */
  problem: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "problem".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    body: string;
    /**
     * What goes wrong when brands scale unaided.
     */
    wall?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    turnLead: string;
    turnAccent: string;
    chartTitle: string;
    chartGood: string;
    chartBad: string;
  };
  /**
   * Renders the "Video testimonials" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  videoTestimonials: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "testimonials".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    lede: string;
    /**
     * Fill exactly one video source per entry. YouTube ID wins, then Vimeo, then MP4.
     */
    items?:
      | {
          name: string;
          role: string;
          company: string;
          quote: string;
          metrics?:
            | {
                /**
                 * e.g. 300+, ₹250 Cr, 14 mo
                 */
                value: string;
                label: string;
                id?: string | null;
              }[]
            | null;
          youtubeId?: string | null;
          vimeoId?: string | null;
          /**
           * Full URL to an .mp4
           */
          mp4?: string | null;
          /**
           * Thumbnail shown before the video plays.
           */
          poster?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Renders the "Case studies" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  caseStudies: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "case-studies".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    lede: string;
    items?:
      | {
          tag: string;
          brand: string;
          challenge: string;
          built: string;
          metrics?:
            | {
                /**
                 * e.g. 300+, ₹250 Cr, 14 mo
                 */
                value: string;
                label: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Renders the "The Engine" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  engine: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "engine".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    lede: string;
    pillars?:
      | {
          /**
           * Displayed number, e.g. 01
           */
          idx: string;
          title: string;
          body: string;
          /**
           * Completes the sentence 'You get …'
           */
          get: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Renders the "Tracks" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  tracks: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "tracks".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    items?:
      | {
          tag: string;
          title: string;
          points?:
            | {
                value: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    note: string;
  };
  /**
   * Renders the "Who it's for" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  fit: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "fit".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    yes: {
      title: string;
      points?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    no: {
      title: string;
      points?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Renders the "Offer" section, which is always part of the page.
   */
  offer: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "offer".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    slots: {
      taken: number;
      total: number;
    };
    cardTitle: string;
    cardSub: string;
    includes?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Line items and their stated value.
     */
    valueStack?:
      | {
          /**
           * e.g. 300+, ₹250 Cr, 14 mo
           */
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    totalValue: string;
    priceLead: string;
    price: string;
    priceSuffix: string;
    credit: string;
    cta: string;
    anchor: string;
    /**
     * Bolded lead-in, e.g. 'The done-for-you engagement'
     */
    engagementLead: string;
    engagementNote: string;
  };
  /**
   * Renders the "Bonuses" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  bonuses: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "bonuses".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    items?:
      | {
          tag: string;
          title: string;
          value: string;
          body: string;
          id?: string | null;
        }[]
      | null;
    total: string;
  };
  /**
   * Renders the "Team" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  team: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "team".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    /**
     * Each entry renders as its own paragraph.
     */
    body?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Portrait crop (4:5). Left empty, the section shows a styled placeholder box.
     */
    photo?: (number | null) | Media;
  };
  /**
   * Renders the "Guarantee" section, which is always part of the page.
   */
  guarantee: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "guarantee".
     */
    targetId?: string | null;
    title: string;
    body: string;
  };
  inaction: {
    wait: {
      title: string;
      points?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    act: {
      title: string;
      points?:
        | {
            value: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  /**
   * Renders the "FAQ" section. Remove every entry and the section — along with any navigation link pointing at it — drops off the page.
   */
  faq: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "faq".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    items?:
      | {
          q: string;
          a: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Renders the "Final CTA" section, which is always part of the page.
   */
  finalCta: {
    /**
     * Lower-case letters, numbers and hyphens — this becomes the #anchor a navigation link scrolls to. Leave it blank to use "apply".
     */
    targetId?: string | null;
    /**
     * Small eyebrow label above the title.
     */
    kicker: string;
    title: string;
    body: string;
    cta: string;
    trust?:
      | {
          value: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        suffix?: T;
        tagline?: T;
      };
  navLinks?:
    | T
    | {
        label?: T;
        targetId?: T;
        id?: T;
      };
  announcement?:
    | T
    | {
        live?: T;
        countdownLabel?: T;
      };
  applicationsCloseAt?: T;
  stickyBar?:
    | T
    | {
        title?: T;
        sub?: T;
        cta?: T;
      };
  footer?:
    | T
    | {
        company?: T;
        blurb?: T;
        legal?: T;
      };
  hero?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        titleLead?: T;
        titleAccent?: T;
        lede?: T;
        checks?:
          | T
          | {
              value?: T;
              id?: T;
            };
        glance?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        cta?: T;
        ctaNote?: T;
        credential?:
          | T
          | {
              initial?: T;
              logo?: T;
              headline?: T;
              body?: T;
            };
        mapCaption?: T;
      };
  proofTargetId?: T;
  proofStats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  clientsTargetId?: T;
  showcaseHeading?: T;
  problem?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        body?: T;
        wall?:
          | T
          | {
              value?: T;
              id?: T;
            };
        turnLead?: T;
        turnAccent?: T;
        chartTitle?: T;
        chartGood?: T;
        chartBad?: T;
      };
  videoTestimonials?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        lede?: T;
        items?:
          | T
          | {
              name?: T;
              role?: T;
              company?: T;
              quote?: T;
              metrics?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              youtubeId?: T;
              vimeoId?: T;
              mp4?: T;
              poster?: T;
              id?: T;
            };
      };
  caseStudies?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        lede?: T;
        items?:
          | T
          | {
              tag?: T;
              brand?: T;
              challenge?: T;
              built?: T;
              metrics?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  engine?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        lede?: T;
        pillars?:
          | T
          | {
              idx?: T;
              title?: T;
              body?: T;
              get?: T;
              id?: T;
            };
      };
  tracks?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        items?:
          | T
          | {
              tag?: T;
              title?: T;
              points?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
              id?: T;
            };
        note?: T;
      };
  fit?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        yes?:
          | T
          | {
              title?: T;
              points?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
        no?:
          | T
          | {
              title?: T;
              points?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
      };
  offer?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        slots?:
          | T
          | {
              taken?: T;
              total?: T;
            };
        cardTitle?: T;
        cardSub?: T;
        includes?:
          | T
          | {
              value?: T;
              id?: T;
            };
        valueStack?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        totalValue?: T;
        priceLead?: T;
        price?: T;
        priceSuffix?: T;
        credit?: T;
        cta?: T;
        anchor?: T;
        engagementLead?: T;
        engagementNote?: T;
      };
  bonuses?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        items?:
          | T
          | {
              tag?: T;
              title?: T;
              value?: T;
              body?: T;
              id?: T;
            };
        total?: T;
      };
  team?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        body?:
          | T
          | {
              value?: T;
              id?: T;
            };
        photo?: T;
      };
  guarantee?:
    | T
    | {
        targetId?: T;
        title?: T;
        body?: T;
      };
  inaction?:
    | T
    | {
        wait?:
          | T
          | {
              title?: T;
              points?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
        act?:
          | T
          | {
              title?: T;
              points?:
                | T
                | {
                    value?: T;
                    id?: T;
                  };
            };
      };
  faq?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        items?:
          | T
          | {
              q?: T;
              a?: T;
              id?: T;
            };
      };
  finalCta?:
    | T
    | {
        targetId?: T;
        kicker?: T;
        title?: T;
        body?: T;
        cta?: T;
        trust?:
          | T
          | {
              value?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}